data:
  raw_path: data/raw/bike_sharing_modified_dvc.csv
  processed_path: data/processed/train.parquet

features:
  scaler: standard

train:
  test_size: 0.2
  random_state: 42

eval:
  cv_folds: 5
  metrics: [rmse, mae, r2]
