data:
  raw_path: data/raw/bike_sharing_original.csv
  processed_path: data/processed/train.parquet

features:
  scaler: standard

train:
  model_type: random_forest
  n_estimators: 200
  max_depth: 12
  test_size: 0.2
  random_state: 42

eval:
  metrics: [rmse, mae, r2]
